export type Lang = "en" | "he";

export const translations = {
  en: {
    // Nav
    nav_home: "Home",
    nav_requests: "Requests",
    nav_availability: "Schedule",
    nav_profile: "Profile",
    nav_preview: "Preview",
    nav_signout: "Sign out",
    nav_areyousure: "Are you sure?",
    nav_yes_signout: "Yes, sign out",
    nav_cancel: "Cancel",
    nav_loading: "Loading…",
    // Status badges
    status_approved: "approved",
    status_pending: "pending",
    status_rejected: "rejected",
    status_suspended: "suspended",
    // Dashboard
    dash_under_review_title: "Application under review",
    dash_under_review_body: "You'll receive an email once your application is approved.",
    dash_rejected_title: "Application not approved",
    dash_rejected_body: "Please contact support for more information.",
    dash_suspended_title: "Account suspended",
    dash_suspended_body: "Contact support to resolve this.",
    dash_title: "Dashboard",
    dash_welcome: "Welcome back!",
    dash_new_requests: "New requests",
    dash_view_all: "View all",
    dash_no_pending: "No pending requests right now.",
    dash_upcoming: "Upcoming cleans",
    dash_no_upcoming: "No upcoming cleans.",
    dash_in_today: "Today",
    dash_in_tomorrow: "Tomorrow",
    dash_in_days: "in {n} days",
    dash_past: "Past cleans",
    dash_no_past: "No past cleans yet.",
    dash_complete: "Complete",
    dash_completing: "Completing…",
    dash_completed: "Completed",
    dash_updates: "Updates",
    rate_title: "Rate this customer",
    rate_saved: "Your rating",
    rate_saving: "Saving…",
    rate_error: "Could not save your rating. Please try again.",
    rate_review_placeholder: "Leave a review of this host for other cleaners (optional)",
    rate_review_save: "Save review",
    dash_updates_cancelled: "Booking cancelled",
    dash_updates_seen: "I have seen this",
    dash_updates_seen_all: "I've seen all",
    dash_updates_dismissing: "Dismissing…",
    dash_when_today: "Today",
    dash_when_tomorrow: "Tomorrow",
    dash_when_in: "In",
    dash_when_days: "days",
    // Requests
    req_empty: "No booking requests yet.",
    req_title: "Requests",
    req_subtitle: "Respond to pending requests within 24 hours.",
    req_awaiting: "Awaiting response",
    req_past: "Past requests",
    req_watch: "View",
    req_date: "Date",
    req_time: "Time",
    req_duration: "Duration",
    req_duration_not_sure: "Not sure",
    req_service: "Service",
    req_address: "Address",
    req_notes: "Notes",
    req_customer_phone: "Customer phone",
    req_avail_window: "Customer available",
    req_accepting: "Accepting…",
    req_accept: "Accept",
    req_accept_confirm: "Accept this request?",
    req_accept_yes: "Yes, accept",
    req_accept_no: "Not yet",
    req_declining: "Declining…",
    req_decline: "Decline",
    req_decline_confirm: "Decline this request?",
    req_decline_yes: "Yes, decline",
    req_decline_no: "Keep it",
    req_done: "Done",
    req_cancel: "Cancel booking",
    req_cancel_confirm: "Cancel this clean? This can't be undone.",
    req_cancel_yes: "Yes, cancel",
    req_cancel_no: "Keep it",
    req_cancelling: "Cancelling…",
    req_cancel_error: "Could not cancel. Please try again.",
    req_expired: "Expired",
    req_h: "h",
    req_m_left: "m left",
    req_customer: "Customer",
    req_view_profile: "View profile",
    req_back_requests: "← Back to requests",
    req_back_dashboard: "← Back to dashboard",
    req_edit: "Edit",
    req_edit_title: "Edit booking",
    req_edit_add_note: "Add a note",
    req_edit_note_placeholder: "Add a note for the customer…",
    req_edit_save: "Save changes",
    req_edit_saving: "Saving…",
    req_edit_cancel: "Cancel",
    req_edit_outside_warning:
      "This time is outside your marked availability for that day. Are you sure you want to save it?",
    req_edit_save_anyway: "Save anyway",
    svc_residential: "Residential",
    svc_commercial: "Commercial",
    // Availability
    avail_title: "Availability",
    avail_legend_available: "Available",
    avail_legend_booked: "Booked",
    avail_legend_pending: "Pending",
    avail_legend_none: "Not available",
    avail_welcome_title: "Welcome, {name}! 👋",
    avail_welcome_body:
      "Cindy is here to help you find work that fits your schedule.\n\nStart by choosing the days you're available. Once your profile is approved, hosts can start finding you right away.\n\nLet's get you started!",
    avail_welcome_close: "Close",
    avail_weekly: "Weekly schedule",
    avail_weekly_body: "Hours that repeat every week. Customers can book you on these days automatically.",
    avail_specific: "Specific dates",
    avail_specific_body: "Add availability for a particular date — useful for one-off days or exceptions.",
    avail_add_recurring: "Add recurring hours",
    avail_every: "Every",
    avail_add: "Add",
    avail_adding: "Adding…",
    avail_cancel: "Cancel",
    avail_past_day: "Past day",
    avail_no_hours_past: "No hours were set for this day.",
    avail_no_slots_yet: "No slots yet",
    avail_booked: "✓ Booked",
    avail_recurring_label: "↻ Weekly recurring",
    avail_add_section: "Add availability",
    avail_from: "From",
    avail_to: "To",
    avail_note_label: "Note for hosts (optional)",
    avail_note_placeholder: "Anything hosts should know about this day, or in general…",
    avail_end_after_start: "End time must be after start time.",
    avail_short_warning: "This slot is an hour or less — that may be too short for most bookings.",
    avail_requests_for_day: "Pending requests",
    avail_pending_request: "pending request",
    avail_pending_requests: "pending requests",
    slot_morning: "Morning",
    slot_noon: "Noon",
    slot_evening: "Evening",
    // Days (short / full)
    day_sun: "Sun", day_mon: "Mon", day_tue: "Tue", day_wed: "Wed",
    day_thu: "Thu", day_fri: "Fri", day_sat: "Sat",
    day_sunday: "Sunday", day_monday: "Monday", day_tuesday: "Tuesday",
    day_wednesday: "Wednesday", day_thursday: "Thursday",
    day_friday: "Friday", day_saturday: "Saturday",
    // Months (full / short)
    month_jan: "January",   month_feb: "February",  month_mar: "March",
    month_apr: "April",     month_may: "May",        month_jun: "June",
    month_jul: "July",      month_aug: "August",     month_sep: "September",
    month_oct: "October",   month_nov: "November",   month_dec: "December",
    month_jan_s: "Jan",  month_feb_s: "Feb",  month_mar_s: "Mar",
    month_apr_s: "Apr",  month_may_s: "May",  month_jun_s: "Jun",
    month_jul_s: "Jul",  month_aug_s: "Aug",  month_sep_s: "Sep",
    month_oct_s: "Oct",  month_nov_s: "Nov",  month_dec_s: "Dec",
    // Profile
    prof_title: "Profile",
    prof_subtitle: "Keep your profile updated so customers can find and trust you.",
    prof_photo: "Profile photo",
    prof_full_name: "Full name",
    prof_phone: "Phone",
    prof_bio: "Bio",
    prof_hourly_rate: "Hourly rate (₪)",
    prof_service_radius: "Service radius (km)",
    prof_max_hours: "Max hours per clean",
    prof_max_hours_hint: "Shown on your profile so customers know what to expect — it doesn't limit which bookings you can be sent. Leave blank for no limit.",
    prof_no_limit: "No limit",
    prof_service_types: "Service types",
    prof_address: "Service area address",
    prof_address_hint: "Used to calculate your service coverage area.",
    prof_experience: "Years of experience",
    prof_languages: 'Languages (separated by ",")',
    prof_saved: "Profile saved.",
    prof_saving: "Saving...",
    prof_save: "Save profile",
    prof_min_job_length: "Minimum job length (hrs)",
    prof_min_job_length_hint: "Shown on your profile so customers know what to expect — it doesn't limit which bookings you can be sent.",
    prof_birthdate: "Birthdate",
    prof_day: "Day",
    prof_month: "Month",
    prof_year: "Year",
    prof_other_details: "Other details — not shown on your public profile",
    prof_weekly_freq: "Weekly cleaning frequency",
    prof_weekly_freq_hint: "For our own planning — not shown to customers.",
    prof_has_car: "Do you have a car?",
    prof_gas_returns: "Take gas returns?",
    prof_gas_rate: "Gas rate",
    prof_per_km: "per 1 km",
    prof_work_areas: "Work areas",
    prof_match_preference: "What type of match am I looking for?",
    prof_match_recurring: "A recurring family I keep coming back to",
    prof_match_occasional: "A job once in a while — it does not have to be the same family",
    prof_match_other: "Other",
    prof_yes: "Yes",
    prof_no: "No",
    prof_edit: "Edit",
    prof_no_ratings: "No ratings yet",
    prof_min_job: "Min. job length",
    prof_max_job: "Max. job length",
    prof_houses_cleaned: "Houses cleaned",
    prof_gas_return_stat: "Gas return",
    prof_services_label: "Services",
    prof_looking_for_label: "Looking for",
    prof_not_set: "Not set yet",
    prof_none_selected: "None selected yet",
    prof_pct_complete: "{pct}% complete",
    prof_still_missing: "Still missing: {list}",
    // Gallery
    gallery_title: "Gallery",
    gallery_subtitle: "Photos customers will see on your profile.",
    gallery_uploading: "Uploading…",
    gallery_add: "+ Add photo",
    gallery_empty: "No photos yet.",
    gallery_empty_sub: "Add some to show customers your work.",
    // Preview
    prev_banner: "This is your public profile — as customers see it.",
    prev_edit: "Edit profile →",
    prev_request: "Request for cleaning",
    prev_experience: "Experience",
    prev_radius: "Service radius",
    prev_rate: "Hourly rate",
    prev_about: "About",
    prev_service_types: "Service Types",
    prev_no_bio: "No bio written yet.",
    prev_no_name: "No name set",
    prev_year: "year",
    prev_years: "years",
    // Auth
    auth_welcome: "Welcome back",
    auth_signin_sub: "Sign in to your account",
    auth_email: "Email",
    auth_password: "Password",
    auth_signing_in: "Signing in…",
    auth_signin: "Sign in",
    auth_no_account: "Don't have an account?",
    auth_register: "Register",
    auth_create: "Create account",
    auth_choose: "Choose how you want to use Clean",
    auth_customer: "Customer",
    auth_customer_sub: "Find & book cleaners",
    auth_cleaner: "Cleaner",
    auth_cleaner_sub: "Offer your services",
    auth_creating: "Creating your account…",
    auth_continue: "Continue",
    auth_have_account: "Already have an account?",
    // Cleaner onboarding
    onboard_back: "Go back",
    onboard_title: "Cleaner application",
    onboard_subtitle: "Fill in your details. Our team will review your application within 1–2 business days.",
    onboard_full_name: "Full name",
    onboard_name_error: "Please enter your full name.",
    onboard_phone: "Phone",
    onboard_phone_error: "Please enter a valid phone number.",
    onboard_bio: "Bio",
    onboard_bio_placeholder: "Tell customers about your experience and approach...",
    onboard_experience: "Years of experience",
    onboard_languages: "Languages (comma-separated)",
    onboard_id_doc: "ID document",
    onboard_id_doc_hint: "passport, national ID",
    onboard_id_doc_sub: "PDF, JPG, or PNG. Stored securely.",
    onboard_submitting: "Submitting…",
    onboard_submit: "Submit application",
    onboard_submit_loading: "Submitting application…",
    // Pending page
    pending_title: "Application submitted",
    pending_body: "Our team is reviewing your application and ID document. You'll receive an email once it's approved — usually within 1–2 business days.",
  },
  he: {
    // Nav
    nav_home: "בית",
    nav_requests: "בקשות",
    nav_availability: "לוח זמנים",
    nav_profile: "פרופיל",
    nav_preview: "תצוגה מקדימה",
    nav_signout: "התנתק",
    nav_areyousure: "בטוח?",
    nav_yes_signout: "כן, התנתק",
    nav_cancel: "ביטול",
    nav_loading: "טוען...",
    // Status badges
    status_approved: "מאושר",
    status_pending: "ממתין",
    status_rejected: "נדחה",
    status_suspended: "מושעה",
    // Dashboard
    dash_under_review_title: "הבקשה בבדיקה",
    dash_under_review_body: "תקבל מייל כשהבקשה תאושר.",
    dash_rejected_title: "הבקשה לא אושרה",
    dash_rejected_body: "אנא צור קשר עם התמיכה לפרטים נוספים.",
    dash_suspended_title: "החשבון מושעה",
    dash_suspended_body: "צור קשר עם התמיכה לפתרון הבעיה.",
    dash_title: "לוח בקרה",
    dash_welcome: "ברוך שובך!",
    dash_new_requests: "בקשות חדשות",
    dash_view_all: "הצג הכל",
    dash_no_pending: "אין בקשות ממתינות כרגע.",
    dash_upcoming: "ניקיונות קרובים",
    dash_no_upcoming: "אין ניקיונות קרובים.",
    dash_in_today: "היום",
    dash_in_tomorrow: "מחר",
    dash_in_days: "בעוד {n} ימים",
    dash_past: "ניקיונות קודמים",
    dash_no_past: "אין ניקיונות קודמים עדיין.",
    dash_complete: "סיום",
    dash_completing: "מסיים…",
    dash_completed: "הושלם",
    dash_updates: "עדכונים",
    rate_title: "דרגו את הלקוח",
    rate_saved: "הדירוג שלכם",
    rate_saving: "שומר…",
    rate_error: "לא ניתן היה לשמור את הדירוג. נסו שוב.",
    rate_review_placeholder: "השאירו חוות דעת על המארח/ת עבור מנקים אחרים (לא חובה)",
    rate_review_save: "שמירת חוות דעת",
    dash_updates_cancelled: "ההזמנה בוטלה",
    dash_updates_seen: "ראיתי את זה",
    dash_updates_seen_all: "ראיתי הכל",
    dash_updates_dismissing: "מסיר…",
    dash_when_today: "היום",
    dash_when_tomorrow: "מחר",
    dash_when_in: "בעוד",
    dash_when_days: "ימים",
    // Requests
    req_empty: "אין בקשות הזמנה עדיין.",
    req_title: "בקשות",
    req_subtitle: "הגב לבקשות ממתינות תוך 24 שעות.",
    req_awaiting: "ממתין לתשובה",
    req_past: "בקשות קודמות",
    req_watch: "צפה",
    req_date: "תאריך",
    req_time: "שעה",
    req_duration: "משך",
    req_duration_not_sure: "לא בטוח/ה",
    req_service: "שירות",
    req_address: "כתובת",
    req_notes: "הערות",
    req_customer_phone: "טלפון לקוח",
    req_avail_window: "הלקוח פנוי",
    req_accepting: "מאשר...",
    req_accept: "אשר",
    req_accept_confirm: "לאשר את הבקשה?",
    req_accept_yes: "כן, אשרו",
    req_accept_no: "עוד לא",
    req_declining: "דוחה...",
    req_decline: "דחה",
    req_decline_confirm: "לדחות את הבקשה?",
    req_decline_yes: "כן, דחו",
    req_decline_no: "השאירו",
    req_done: "סיום",
    req_cancel: "ביטול הזמנה",
    req_cancel_confirm: "לבטל את הניקיון? לא ניתן לבטל פעולה זו.",
    req_cancel_yes: "כן, בטלו",
    req_cancel_no: "השאירו",
    req_cancelling: "מבטל…",
    req_cancel_error: "לא ניתן היה לבטל. נסו שוב.",
    req_expired: "פג תוקף",
    req_h: "ש׳",
    req_m_left: "ד׳ נותרו",
    req_customer: "לקוח",
    req_view_profile: "צפייה בפרופיל",
    req_back_requests: "→ חזרה לבקשות",
    req_back_dashboard: "→ חזרה ללוח הבקרה",
    req_edit: "עריכה",
    req_edit_title: "עריכת הזמנה",
    req_edit_add_note: "הוספת הערה",
    req_edit_note_placeholder: "הוסיפו הערה ללקוח…",
    req_edit_save: "שמירת שינויים",
    req_edit_saving: "שומר…",
    req_edit_cancel: "ביטול",
    req_edit_outside_warning:
      "השעה הזו נמצאת מחוץ לזמינות שסימנת לאותו יום. בטוחה שברצונך לשמור אותה?",
    req_edit_save_anyway: "שמירה בכל זאת",
    svc_residential: "מגורים",
    svc_commercial: "מסחרי",
    // Availability
    avail_title: "זמינות",
    avail_legend_available: "פנוי",
    avail_legend_booked: "מוזמן",
    avail_legend_pending: "ממתין",
    avail_legend_none: "לא זמין",
    avail_welcome_title: "ברוכים הבאים, {name}! 👋",
    avail_welcome_body:
      "סינדי כאן כדי לעזור לך למצוא עבודה שמתאימה ללוח הזמנים שלך.\n\nהתחילו בבחירת הימים שבהם אתם זמינים. לאחר אישור הפרופיל שלכם, לקוחות יוכלו למצוא אתכם מיד.\n\nבואו נתחיל!",
    avail_welcome_close: "סגירה",
    avail_weekly: "לוח שבועי",
    avail_weekly_body: "שעות שחוזרות כל שבוע. לקוחות יכולים להזמין אותך בימים אלה אוטומטית.",
    avail_specific: "תאריכים ספציפיים",
    avail_specific_body: "הוסף זמינות לתאריך מסוים — שימושי לימים חד-פעמיים או חריגים.",
    avail_add_recurring: "הוסף שעות חוזרות",
    avail_every: "כל",
    avail_add: "הוסף",
    avail_adding: "מוסיף...",
    avail_cancel: "ביטול",
    avail_past_day: "יום עבר",
    avail_no_hours_past: "לא נקבעו שעות ליום הזה.",
    avail_no_slots_yet: "אין עדיין משבצות זמינות",
    avail_booked: "✓ מוזמן",
    avail_recurring_label: "↻ חוזר שבועי",
    avail_add_section: "הוסף זמינות",
    avail_from: "משעה",
    avail_to: "עד שעה",
    avail_note_label: "הערה ללקוחות (לא חובה)",
    avail_note_placeholder: "משהו שכדאי שהלקוחות ידעו על היום הזה, או באופן כללי…",
    avail_end_after_start: "שעת הסיום חייבת להיות אחרי שעת ההתחלה.",
    avail_short_warning: "המשבצת היא שעה או פחות — ייתכן שזה קצר מדי עבור רוב ההזמנות.",
    avail_requests_for_day: "בקשות ממתינות",
    avail_pending_request: "בקשה ממתינה",
    avail_pending_requests: "בקשות ממתינות",
    slot_morning: "בוקר",
    slot_noon: "צהריים",
    slot_evening: "ערב",
    // Days (short / full)
    day_sun: "א׳", day_mon: "ב׳", day_tue: "ג׳", day_wed: "ד׳",
    day_thu: "ה׳", day_fri: "ו׳", day_sat: "ש׳",
    day_sunday: "ראשון", day_monday: "שני", day_tuesday: "שלישי",
    day_wednesday: "רביעי", day_thursday: "חמישי",
    day_friday: "שישי", day_saturday: "שבת",
    // Months (full / short)
    month_jan: "ינואר",   month_feb: "פברואר",  month_mar: "מרץ",
    month_apr: "אפריל",   month_may: "מאי",     month_jun: "יוני",
    month_jul: "יולי",    month_aug: "אוגוסט",  month_sep: "ספטמבר",
    month_oct: "אוקטובר", month_nov: "נובמבר",  month_dec: "דצמבר",
    month_jan_s: "ינו׳", month_feb_s: "פבר׳", month_mar_s: "מרץ",
    month_apr_s: "אפר׳", month_may_s: "מאי",  month_jun_s: "יונ׳",
    month_jul_s: "יול׳", month_aug_s: "אוג׳", month_sep_s: "ספט׳",
    month_oct_s: "אוק׳", month_nov_s: "נוב׳", month_dec_s: "דצמ׳",
    // Profile
    prof_title: "פרופיל",
    prof_subtitle: "עדכן את הפרופיל שלך כדי שלקוחות יוכלו למצוא אותך ולסמוך עליך.",
    prof_photo: "תמונת פרופיל",
    prof_full_name: "שם מלא",
    prof_phone: "טלפון",
    prof_bio: "תיאור",
    prof_hourly_rate: "תעריף לשעה (₪)",
    prof_service_radius: 'רדיוס שירות (ק"מ)',
    prof_max_hours: "מקסימום שעות לניקיון",
    prof_max_hours_hint: "מוצג בפרופיל שלך כדי שהלקוחות ידעו למה לצפות — הוא לא מגביל אילו בקשות הזמנה יישלחו אליך. השאירו ריק ללא הגבלה.",
    prof_no_limit: "ללא הגבלה",
    prof_service_types: "סוגי שירות",
    prof_address: "כתובת אזור שירות",
    prof_address_hint: "משמש לחישוב אזור הכיסוי שלך.",
    prof_experience: "שנות ניסיון",
    prof_languages: 'שפות (מופרדות על ידי ",")',
    prof_saved: "הפרופיל נשמר.",
    prof_saving: "שומר...",
    prof_save: "שמור פרופיל",
    prof_min_job_length: "משך זמן מינימלי לעבודה (שעות)",
    prof_min_job_length_hint: "מוצג בפרופיל שלך כדי שהלקוחות ידעו למה לצפות — הוא לא מגביל אילו בקשות הזמנה יישלחו אליך.",
    prof_birthdate: "תאריך לידה",
    prof_day: "יום",
    prof_month: "חודש",
    prof_year: "שנה",
    prof_other_details: "פרטים נוספים — לא מוצגים בפרופיל הציבורי שלך",
    prof_weekly_freq: "תדירות ניקיון שבועית",
    prof_weekly_freq_hint: "לתכנון שלנו בלבד — לא מוצג ללקוחות.",
    prof_has_car: "יש לך רכב?",
    prof_gas_returns: "החזר דלק?",
    prof_gas_rate: "תעריף החזר דלק",
    prof_per_km: 'לכל 1 ק"מ',
    prof_work_areas: "אזורי עבודה",
    prof_match_preference: "איזה סוג התאמה אתה מחפש?",
    prof_match_recurring: "משפחה קבועה שאני חוזר/ת אליה",
    prof_match_occasional: "עבודה מדי פעם — לא חייבת להיות אותה משפחה",
    prof_match_other: "אחר",
    prof_yes: "כן",
    prof_no: "לא",
    prof_edit: "עריכה",
    prof_no_ratings: "אין דירוגים עדיין",
    prof_min_job: "משך מינימלי",
    prof_max_job: "משך מקסימלי",
    prof_houses_cleaned: "בתים שנוקו",
    prof_gas_return_stat: "החזר דלק",
    prof_services_label: "שירותים",
    prof_looking_for_label: "מחפש/ת",
    prof_not_set: "טרם נקבע",
    prof_none_selected: "לא נבחר עדיין",
    prof_pct_complete: "{pct}% הושלם",
    prof_still_missing: "עדיין חסר: {list}",
    // Gallery
    gallery_title: "גלריה",
    gallery_subtitle: "תמונות שלקוחות יראו בפרופיל שלך.",
    gallery_uploading: "מעלה...",
    gallery_add: "+ הוסף תמונה",
    gallery_empty: "אין תמונות עדיין.",
    gallery_empty_sub: "הוסף כמה כדי להראות ללקוחות את עבודתך.",
    // Preview
    prev_banner: "זהו הפרופיל הציבורי שלך — כפי שלקוחות רואים אותו.",
    prev_edit: "ערוך פרופיל ←",
    prev_request: "בקש ניקיון",
    prev_experience: "ניסיון",
    prev_radius: "רדיוס שירות",
    prev_rate: "תעריף לשעה",
    prev_about: "אודות",
    prev_service_types: "סוגי שירות",
    prev_no_bio: "לא נכתב תיאור עדיין.",
    prev_no_name: "לא נקבע שם",
    prev_year: "שנה",
    prev_years: "שנים",
    // Auth
    auth_welcome: "ברוך שובך",
    auth_signin_sub: "כניסה לחשבון שלך",
    auth_email: "אימייל",
    auth_password: "סיסמה",
    auth_signing_in: "נכנס...",
    auth_signin: "כניסה",
    auth_no_account: "אין לך חשבון?",
    auth_register: "הרשמה",
    auth_create: "צור חשבון",
    auth_choose: "בחר כיצד אתה רוצה להשתמש ב-Clean",
    auth_customer: "לקוח",
    auth_customer_sub: "מצא והזמן מנקים",
    auth_cleaner: "מנקה",
    auth_cleaner_sub: "הצע את שירותיך",
    auth_creating: "יוצר את החשבון שלך...",
    auth_continue: "המשך",
    auth_have_account: "כבר יש לך חשבון?",
    // Cleaner onboarding
    onboard_back: "חזור",
    onboard_title: "בקשת מנקה",
    onboard_subtitle: "מלא את הפרטים שלך. הצוות שלנו יבדוק את בקשתך תוך 1–2 ימי עסקים.",
    onboard_full_name: "שם מלא",
    onboard_name_error: "אנא הזן את שמך המלא.",
    onboard_phone: "טלפון",
    onboard_phone_error: "אנא הזן מספר טלפון תקין.",
    onboard_bio: "תיאור",
    onboard_bio_placeholder: "ספר ללקוחות על הניסיון והגישה שלך...",
    onboard_experience: "שנות ניסיון",
    onboard_languages: "שפות (מופרדות בפסיק)",
    onboard_id_doc: "מסמך זיהוי",
    onboard_id_doc_hint: "דרכון, תעודת זהות",
    onboard_id_doc_sub: "PDF, JPG, או PNG. מאוחסן בצורה מאובטחת.",
    onboard_submitting: "שולח...",
    onboard_submit: "שלח בקשה",
    onboard_submit_loading: "שולח בקשה...",
    // Pending page
    pending_title: "הבקשה נשלחה",
    pending_body: "הצוות שלנו בודק את בקשתך ומסמך הזיהוי. תקבל מייל כשיאושר — בדרך כלל תוך 1–2 ימי עסקים.",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function t(lang: Lang, key: TranslationKey): string {
  return translations[lang][key];
}
